apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "tiered-node-scheduler.fullname" . }}-lease
  namespace: {{ .Values.leaderElection.resourceNamespace | default .Release.Namespace }}
  labels:
    {{- include "tiered-node-scheduler.labels" . | nindent 4 }}
rules:
  - apiGroups: ["coordination.k8s.io"]
    resources: ["leases"]
    verbs: ["get", "list", "watch", "create", "update", "delete"]
